### ISSUE TITLE
Error: Cannot find module 'ip'

### ISSUE THREAD

**Issue by sohnkarlsruhe** [Samfox2/homebridge-videodoorbell#2]
[2017-12-11 10:22:14] ERROR LOADING PLUGIN homebridge-videodoorbell:
[2017-12-11 10:22:14] Error: Cannot find module 'ip'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-videodoorbell/ffmpeg.js:5:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

can you help me? ffmpeg is installed. 

`{
	"platform": "Video-doorbell",
	"cameras": [{
		"name": "Klingel",
		"videoConfig": {
			"source": "-re -i rtsp://ghxxx01:Kxxxx@192.168.0.100:554/mpeg/media.amp",
			"stillImageSource": "-i http://ghxxx5c@192.168.0.100/bha-api/image.cgi",
			"maxStreams": 2,
			"maxWidth": 1280,
			"maxHeight": 720,
			"maxFPS": 30,
			"port": 5005
		}
	}]
}`

**Comment by Samfox2** [comment]
Looks like the module "ip" is missing.
You can install it with the following command:

npm install ip

**Comment by sohnkarlsruhe** [comment]
thanks, that was too easy for me :-)
